### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'ptp'

### ISSUE THREAD

**Issue by HamletShaoE** [a-slide/pycoQC#112]
Hi, I am using pycoQC on centOS. I come across a problem. Is there any clue that I may have been doing to wrong?
[shaoyi@login02 result]$ pycoQC -f sequencing_summary.txt --outfile pycoQC/pycoQC.html
PARSE CONFIGURATION FILE
PARSE DATA FILES
Import raw data from sequencing summary files
        35,885 reads found in initial file
Verify fields and discard unused columns
        1D Run type
Drop lines containing NA values
        0 reads discarded
Sort run IDs by decreasing throughput
Traceback (most recent call last):
  File "/usr/nzx-cluster/apps/pycoQC/python-scripts/pycoQC", line 12, in <module>
    sys.exit(main_pycoQC())
  File "/usr/nzx-cluster/apps/anaconda3/5.3.1/envs/pycoQC/lib/python3.6/site-packages/pycoQC/cli.py", line 169, in main_pycoQC
    title=args.title)
  File "/usr/nzx-cluster/apps/anaconda3/5.3.1/envs/pycoQC/lib/python3.6/site-packages/pycoQC/cli.py", line 196, in generate_report
    filter_calibration=filter_calibration)
  File "/usr/nzx-cluster/apps/anaconda3/5.3.1/envs/pycoQC/lib/python3.6/site-packages/pycoQC/pycoQC.py", line 166, in __init__
    d[run_id] = len(sdf)/sdf["start_time"].ptp()
  File "/usr/nzx-cluster/apps/anaconda3/5.3.1/envs/pycoQC/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'ptp'

**Comment by a-slide** [comment]
Hi @HamletShaoE 
Could you let me know which version of pycoQC you are using ?
Thanks

**Comment by HamletShaoE** [comment]
@a-slide I am using v2.2.3 pycoQC and using Python 3.6
[shaoyi@login02 ~]$ pycoQC --version
pycoQC v2.2.3
[shaoyi@login02 ~]$ python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29)

**Comment by a-slide** [comment]
Could you open to the last version v2.5.0.21 ?
It is now available on bioconda

**Comment by a-slide** [comment]
Assumed fixed

**Comment by HamletShaoE** [comment]
Yes, after a more recent version. This problem is solved. Sorry I was into the analysis and forget to reply.

**Comment by a-slide** [comment]
No worries. Thanks for your feedback.
Cheers
Ad
