### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by chanster-j** [a-slide/pycoQC#152]
**Describe the bug**
Hi all, I am very new the bioinformactic space and I am setout to learn how to QC nanopore data. I have managed to install pycoQC but can not get it to run sucessfully. Can someone explain what TypeError is?

TypeError: unsupported format string passed to NoneType.__format__

I used commend pycoQC --summary_file sequencing_summary.txt -o testing.html

**Desktop (please complete the following information):**

* OS 14.6.1

**Additional context**

Checking arguments values
Check input data files
Parse data files
Merge data
Cleaning data
	Discarding lines containing NA values
		0 reads discarded
	Filtering out zero length reads
		0 reads discarded
	Sorting run IDs by decreasing throughput
		Run-id order ['20b693e860160204aba548dd772bcb8033c74806']
	Reordering runids
		Processing reads with Run_ID 20b693e860160204aba548dd772bcb8033c74806 / time offset: 0
	Cleaning up low frequency barcodes
		162 reads with low frequency barcode unset
	Cast value to appropriate type
	Reindexing dataframe by read_ids
		5,063,791 Final valid reads
Loading plotting interface
Generating HTML report
	Parsing html config file
	Running method summary
		Computing plot
/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/pycoQC_plot.py:1471: RuntimeWarning:

overflow encountered in scalar add

Traceback (most recent call last):
  File "/Users/jc/miniconda3/envs/pycoQC/bin/pycoQC", line 12, in <module>
    sys.exit(main_pycoQC())
             ^^^^^^^^^^^^^
  File "/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/__main__.py", line 109, in main_pycoQC
    pycoQC (
  File "/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/pycoQC.py", line 148, in pycoQC
    reporter.html_report(
  File "/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/pycoQC_report.py", line 84, in html_report
    fig = method(**method_args)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/pycoQC_plot.py", line 188, in summary
    lab1, dd1 = self.__summary_data (df_level="all", groupby=groupby)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/pycoQC_plot.py", line 257, in __summary_data
    cells.append (self.__df_to_cell(df))
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jc/miniconda3/envs/pycoQC/lib/python3.12/site-packages/pycoQC/pycoQC_plot.py", line 277, in __df_to_cell
    l.append ("{:,.2f}".format(self._compute_N50(df["read_len"])))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__

**Comment by Joshtron** [comment]
I am facing the same issue. It seems that newer runs don't work anymore. I am using MinKNOQ 24.06.8 with Dorado 7.4.13, pycoQC v2.5.0.3 and python 3.12.5.
