### ISSUE TITLE
Error when using pycoQC on small files

### ISSUE THREAD

**Issue by tleonardi** [a-slide/pycoQC#35]
If the sequencing_summary.txt files only contains a few reads, the binning in __output_over_time_data() fails:

```PARSE CONFIGURATION FILE
PARSE DATA FILES
GENERATES PLOTS
Traceback (most recent call last):
  File "/home/nanopore/.local/bin/pycoQC", line 11, in <module>
    sys.exit(main())
  File "/home/nanopore/.local/lib/python3.6/site-packages/pycoQC/cli.py", line 108, in main
    verbose_level=args.verbose_level)
  File "/home/nanopore/.local/lib/python3.6/site-packages/pycoQC/cli.py", line 143, in generate_report
    fig = method(**method_args)
  File "/home/nanopore/.local/lib/python3.6/site-packages/pycoQC/pycoQC.py", line 513, in output_over_time
    dd1, ld1 = args=self.__output_over_time_data (all_df, level="reads")
  File "/home/nanopore/.local/lib/python3.6/site-packages/pycoQC/pycoQC.py", line 558, in __output_over_time_data
    t = np.digitize (t, bins=x, right=True)
ValueError: bins must have non-zero length
```

**Comment by a-slide** [comment]
Fixed in dev branch https://github.com/a-slide/pycoQC/commit/2038da02026f57b96d9854da410abebbd8b3cbfc
